base_model_path: ./examples/base_model
output_dir: ./benchmarks/ckpts/stage1
train_jsonl: ./examples/data/train_stage1.jsonl
val_jsonl: ./examples/data/val.jsonl
image_root: .
seed: 42
epochs: 1
batch_size: 8
grad_accum: 1
precision: bf16
lr: 1.0e-4
mm_lr: 5.0e-4
weight_decay: 0.05
warmup_ratio: 0.05
clip_grad_norm: 1.0
omega: 0.3
tau: 0.8
alpha_mid: 0.2
alpha_deep: 0.1
relay_ratio: 0.02
use_keynorm: true
freeze_vision_encoder: true
freeze_llm: true
train_projector: true
train_vif_block: true
